import {
  Equipment,
  WeeklyUpdate,
  HealthTrendData,
  UptimeData,
  User,
  Alarm,
  PredictiveTask,
  SystemRanking,
  EnergyData,
  IEERData,
  WaterData,
  MonthlySummary,
  EquipmentMonthlySnapshot,
  SiteLocation,
  SiteMonthlySnapshot
} from '../types';
import { westCorpSite } from './westCorpData';

export const mockUser: User = {
  "id": "admin-1",
  "name": "Vitor Fantoni",
  "email": "proactive.service.latam@coolautomation.com",
  "role": "admin",
  "password": "admin123",
  "createdAt": "2026-06-29",
  "clientAccess": [
    "*"
  ]
};

export const mockUsers: User[] = [
  {
    "id": "admin-1",
    "name": "Vitor Fantoni",
    "email": "proactive.service.latam@coolautomation.com",
    "role": "admin",
    "password": "admin123",
    "createdAt": "2026-06-29",
    "clientAccess": [
      "*"
    ]
  },
  {
    "id": "admin-2",
    "name": "Edson",
    "email": "edson@coolautomation.com",
    "role": "admin",
    "password": "admin123",
    "createdAt": "2026-06-29",
    "clientAccess": [
      "*"
    ]
  },
  {
    "id": "manager-1",
    "name": "Gerente Serasa",
    "email": "gerente@serasaexperian.com",
    "role": "manager",
    "password": "gerente123",
    "createdAt": "2026-06-29",
    "clientAccess": [
      "Serasa Experian"
    ]
  }
];

export const mockEquipment: Equipment[] = [
  {
    "id": "1",
    "name": "07 a 50 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.87,
    "availability": 97.0,
    "comfort": 92.5,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "2",
    "name": "R24.05-FLORIPA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.13,
    "availability": 96.3,
    "comfort": 91.3,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "3",
    "name": "R24.09-NOVA IORQUE",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.18,
    "availability": 95.0,
    "comfort": 90.1,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "4",
    "name": "SECRETÁRIA 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 86.1,
    "availability": 86.8,
    "comfort": 78.9,
    "performance": 85.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "5",
    "name": "SECRETÁRIA 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 85.95,
    "availability": 85.5,
    "comfort": 77.7,
    "performance": 88.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "6",
    "name": "R24.04-SÃO PAULO",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.28,
    "availability": 97.3,
    "comfort": 86.5,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "7",
    "name": "ÁREA VIP 04",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 87.8,
    "availability": 88.5,
    "comfort": 82.5,
    "performance": 86.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "8",
    "name": "ÁREA VIP 03",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.38,
    "availability": 95.3,
    "comfort": 91.3,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "9",
    "name": "ÁREA VIP 01",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.22,
    "availability": 94.0,
    "comfort": 90.1,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "10",
    "name": "ÁREA VIP 02",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.48,
    "availability": 93.3,
    "comfort": 88.9,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "11",
    "name": "R24.01-SÃO CARLOS 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.28,
    "availability": 97.0,
    "comfort": 87.7,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "12",
    "name": "R24.01-SÃO CARLOS 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.53,
    "availability": 96.3,
    "comfort": 86.5,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "13",
    "name": "R24.02-COSTA MESA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.17,
    "availability": 95.0,
    "comfort": 92.5,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "14",
    "name": "R24.03-LONDRES 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.43,
    "availability": 94.3,
    "comfort": 91.3,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "15",
    "name": "R24.03-LONDRES 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.47,
    "availability": 93.0,
    "comfort": 90.1,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "16",
    "name": "COPA EXECUTIVA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 90.93,
    "availability": 94.3,
    "comfort": 84.9,
    "performance": 88.5,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "17",
    "name": "RECEPÇÃO 3",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 87.0,
    "availability": 88.5,
    "comfort": 77.7,
    "performance": 88.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "18",
    "name": "R24.06-RECIFE",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.58,
    "availability": 95.3,
    "comfort": 86.5,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "19",
    "name": "R24.12-AUSTRÁLIA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 90.58,
    "availability": 90.65,
    "comfort": 88.05,
    "performance": 89.2,
    "status": "Verde",
    "mttr": 2.85,
    "totalOccurrences": 1,
    "criticalOccurrences": 1,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "20",
    "name": "R24.10-BLUMENAU",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.68,
    "availability": 93.3,
    "comfort": 91.3,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 1,
    "criticalOccurrences": 1,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "21",
    "name": "R24.08-NOVA LIMA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.27,
    "availability": 97.0,
    "comfort": 90.1,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "22",
    "name": "R24.07-BRASÍLIA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.53,
    "availability": 96.3,
    "comfort": 88.9,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "23",
    "name": "R24.11-DUBLIN",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.58,
    "availability": 95.0,
    "comfort": 87.7,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "24",
    "name": "133 a 157 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 93.15,
    "availability": 95.0,
    "comfort": 90.0,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "25",
    "name": "JANELA 01",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 92.21,
    "availability": 94.0,
    "comfort": 88.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "26",
    "name": "125 a 132 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.12,
    "availability": 92.6,
    "comfort": 87.0,
    "performance": 89.8,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "27",
    "name": "109 a 124 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.18,
    "availability": 91.6,
    "comfort": 85.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "28",
    "name": "JANELA 02",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 87.42,
    "availability": 87.2,
    "comfort": 80.0,
    "performance": 89.5,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "29",
    "name": "93 a 108 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.12,
    "availability": 95.2,
    "comfort": 82.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "30",
    "name": "RECEPÇÃO 1",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 85.97,
    "availability": 86.3,
    "comfort": 80.0,
    "performance": 83.8,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "31",
    "name": "RECEPÇÃO 2",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 85.02,
    "availability": 85.3,
    "comfort": 78.5,
    "performance": 82.7,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "32",
    "name": "SALA DE ENTREVISTA",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 84.81,
    "availability": 83.9,
    "comfort": 77.0,
    "performance": 86.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "33",
    "name": "R24.13-REUNIÃO 13",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 83.22,
    "availability": 82.15,
    "comfort": 74.75,
    "performance": 83.9,
    "status": "Amarelo",
    "mttr": 7.75,
    "totalOccurrences": 30,
    "criticalOccurrences": 30,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "34",
    "name": "R24.14-REUNIÃO 14",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 77.91,
    "availability": 77.0,
    "comfort": 68.0,
    "performance": 74.8,
    "status": "Vermelho",
    "mttr": 13.0,
    "totalOccurrences": 38,
    "criticalOccurrences": 38,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "35",
    "name": "71 a 86 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.27,
    "availability": 94.0,
    "comfort": 82.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "36",
    "name": "JANELA 03",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 92.31,
    "availability": 92.6,
    "comfort": 90.0,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "37",
    "name": "61 a 70 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.37,
    "availability": 91.6,
    "comfort": 88.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "38",
    "name": "51 a 60 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.28,
    "availability": 90.2,
    "comfort": 87.0,
    "performance": 89.8,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "39",
    "name": "CABINES 01 E 02",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.44,
    "availability": 95.2,
    "comfort": 85.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  },
  {
    "id": "40",
    "name": "JANELA 04",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 88.68,
    "availability": 90.8,
    "comfort": 80.0,
    "performance": 89.5,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2025-06-29"
  }
];

export const mockMonthlySummaries: MonthlySummary[] = [
  {
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28",
    "health": 86.17,
    "target": 90,
    "availability": 85.95,
    "mttr": 7.87,
    "totalOccurrences": 46,
    "affectedEquipment": 3
  },
  {
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23",
    "health": 89.03,
    "target": 90,
    "availability": 89.4,
    "mttr": 5.3,
    "totalOccurrences": 24,
    "affectedEquipment": 3
  }
];

export const mockSites: SiteLocation[] = [
  {
    "siteId": "serasa-pdc",
    "nome": "Serasa Experian - PDC",
    "cliente": "Serasa Experian",
    "endereco": "Av. das Nações Unidas, 14401 - Torre Sucupira - 24º andar - Chácara Santo Antônio",
    "cidade": "São Paulo",
    "estado": "SP",
    "latitude": -23.62158,
    "longitude": -46.70275,
    "saudeGeral": 86,
    "disponibilidade": 88,
    "conforto": 84,
    "performance": 85,
    "ocorrenciasCriticas": 3,
    "ultimaAtualizacao": "30/06/2026"
  },
  westCorpSite
];

export const mockSiteMonthlySnapshots: SiteMonthlySnapshot[] = [
  {
    "siteId": "serasa-pdc",
    "nome": "Serasa Experian - PDC",
    "cliente": "Serasa Experian",
    "endereco": "Av. das Nações Unidas, 14401 - Torre Sucupira - 24º andar - Chácara Santo Antônio",
    "cidade": "São Paulo",
    "estado": "SP",
    "latitude": -23.62158,
    "longitude": -46.70275,
    "saudeGeral": 82,
    "disponibilidade": 84,
    "conforto": 81,
    "performance": 80,
    "ocorrenciasCriticas": 3,
    "ultimaAtualizacao": "28/05/2026",
    "monthKey": "2026-05",
    "month": "Mai/26"
  },
  {
    "siteId": "serasa-pdc",
    "nome": "Serasa Experian - PDC",
    "cliente": "Serasa Experian",
    "endereco": "Av. das Nações Unidas, 14401 - Torre Sucupira - 24º andar - Chácara Santo Antônio",
    "cidade": "São Paulo",
    "estado": "SP",
    "latitude": -23.62158,
    "longitude": -46.70275,
    "saudeGeral": 86,
    "disponibilidade": 88,
    "conforto": 84,
    "performance": 85,
    "ocorrenciasCriticas": 3,
    "ultimaAtualizacao": "30/06/2026",
    "monthKey": "2026-06",
    "month": "Jun/26"
  },
  {
    "siteId": "west-corp-alameda-tocantins",
    "nome": "West Corp - Alameda Tocantins",
    "cliente": "West Corp",
    "endereco": "Alameda Tocantins, 350",
    "cidade": "Barueri",
    "estado": "SP",
    "latitude": -23.50221,
    "longitude": -46.85119,
    "saudeGeral": 88,
    "disponibilidade": 92,
    "conforto": 89,
    "performance": 90,
    "ocorrenciasCriticas": 0,
    "ultimaAtualizacao": "31/05/2026",
    "monthKey": "2026-05",
    "month": "Mai/26"
  },
  {
    "siteId": "west-corp-alameda-tocantins",
    "nome": "West Corp - Alameda Tocantins",
    "cliente": "West Corp",
    "endereco": "Alameda Tocantins, 350",
    "cidade": "Barueri",
    "estado": "SP",
    "latitude": -23.50221,
    "longitude": -46.85119,
    "saudeGeral": 88,
    "disponibilidade": 92,
    "conforto": 89,
    "performance": 90,
    "ocorrenciasCriticas": 0,
    "ultimaAtualizacao": "30/06/2026",
    "monthKey": "2026-06",
    "month": "Jun/26"
  }
];

export const mockMonthlyEquipmentSnapshots: EquipmentMonthlySnapshot[] = [
  {
    "id": "1",
    "name": "07 a 50 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.87,
    "availability": 97.0,
    "comfort": 92.5,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "2",
    "name": "R24.05-FLORIPA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.13,
    "availability": 96.3,
    "comfort": 91.3,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "3",
    "name": "R24.09-NOVA IORQUE",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.18,
    "availability": 95.0,
    "comfort": 90.1,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "4",
    "name": "SECRETÁRIA 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 86.1,
    "availability": 86.8,
    "comfort": 78.9,
    "performance": 85.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "5",
    "name": "SECRETÁRIA 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 85.95,
    "availability": 85.5,
    "comfort": 77.7,
    "performance": 88.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "6",
    "name": "R24.04-SÃO PAULO",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.28,
    "availability": 97.3,
    "comfort": 86.5,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "7",
    "name": "ÁREA VIP 04",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 87.8,
    "availability": 88.5,
    "comfort": 82.5,
    "performance": 86.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "8",
    "name": "ÁREA VIP 03",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.38,
    "availability": 95.3,
    "comfort": 91.3,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "9",
    "name": "ÁREA VIP 01",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.22,
    "availability": 94.0,
    "comfort": 90.1,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "10",
    "name": "ÁREA VIP 02",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.48,
    "availability": 93.3,
    "comfort": 88.9,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "11",
    "name": "R24.01-SÃO CARLOS 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.28,
    "availability": 97.0,
    "comfort": 87.7,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "12",
    "name": "R24.01-SÃO CARLOS 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.53,
    "availability": 96.3,
    "comfort": 86.5,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "13",
    "name": "R24.02-COSTA MESA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.17,
    "availability": 95.0,
    "comfort": 92.5,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "14",
    "name": "R24.03-LONDRES 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.43,
    "availability": 94.3,
    "comfort": 91.3,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "15",
    "name": "R24.03-LONDRES 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.47,
    "availability": 93.0,
    "comfort": 90.1,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "16",
    "name": "COPA EXECUTIVA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 90.93,
    "availability": 94.3,
    "comfort": 84.9,
    "performance": 88.5,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "17",
    "name": "RECEPÇÃO 3",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 87.0,
    "availability": 88.5,
    "comfort": 77.7,
    "performance": 88.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "18",
    "name": "R24.06-RECIFE",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.58,
    "availability": 95.3,
    "comfort": 86.5,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "19",
    "name": "R24.12-AUSTRÁLIA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 90.58,
    "availability": 90.65,
    "comfort": 88.05,
    "performance": 89.2,
    "status": "Verde",
    "mttr": 2.85,
    "totalOccurrences": 1,
    "criticalOccurrences": 1,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "20",
    "name": "R24.10-BLUMENAU",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.98,
    "availability": 93.65,
    "comfort": 91.75,
    "performance": 91.3,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "21",
    "name": "R24.08-NOVA LIMA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.27,
    "availability": 97.0,
    "comfort": 90.1,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "22",
    "name": "R24.07-BRASÍLIA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.53,
    "availability": 96.3,
    "comfort": 88.9,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "23",
    "name": "R24.11-DUBLIN",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.58,
    "availability": 95.0,
    "comfort": 87.7,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "24",
    "name": "133 a 157 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 93.15,
    "availability": 95.0,
    "comfort": 90.0,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "25",
    "name": "JANELA 01",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 92.21,
    "availability": 94.0,
    "comfort": 88.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "26",
    "name": "125 a 132 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.12,
    "availability": 92.6,
    "comfort": 87.0,
    "performance": 89.8,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "27",
    "name": "109 a 124 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.18,
    "availability": 91.6,
    "comfort": 85.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "28",
    "name": "JANELA 02",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 87.42,
    "availability": 87.2,
    "comfort": 80.0,
    "performance": 89.5,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "29",
    "name": "93 a 108 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.12,
    "availability": 95.2,
    "comfort": 82.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "30",
    "name": "RECEPÇÃO 1",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 85.97,
    "availability": 86.3,
    "comfort": 80.0,
    "performance": 83.8,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "31",
    "name": "RECEPÇÃO 2",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 85.02,
    "availability": 85.3,
    "comfort": 78.5,
    "performance": 82.7,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "32",
    "name": "SALA DE ENTREVISTA",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 84.81,
    "availability": 83.9,
    "comfort": 77.0,
    "performance": 86.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "33",
    "name": "R24.13-REUNIÃO 13",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 87.65,
    "availability": 87.4,
    "comfort": 81.5,
    "performance": 88.4,
    "status": "Amarelo",
    "mttr": 7.75,
    "totalOccurrences": 15,
    "criticalOccurrences": 15,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "34",
    "name": "R24.14-REUNIÃO 14",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 80.27,
    "availability": 79.8,
    "comfort": 71.6,
    "performance": 77.2,
    "status": "Amarelo",
    "mttr": 13.0,
    "totalOccurrences": 30,
    "criticalOccurrences": 30,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "35",
    "name": "71 a 86 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.27,
    "availability": 94.0,
    "comfort": 82.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "36",
    "name": "JANELA 03",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 92.31,
    "availability": 92.6,
    "comfort": 90.0,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "37",
    "name": "61 a 70 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.37,
    "availability": 91.6,
    "comfort": 88.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "38",
    "name": "51 a 60 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.28,
    "availability": 90.2,
    "comfort": 87.0,
    "performance": 89.8,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "39",
    "name": "CABINES 01 E 02",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.44,
    "availability": 95.2,
    "comfort": 85.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "40",
    "name": "JANELA 04",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 88.68,
    "availability": 90.8,
    "comfort": 80.0,
    "performance": 89.5,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-05-28",
    "monthKey": "2026-05",
    "month": "Mai/26",
    "startDate": "2026-05-11",
    "endDate": "2026-05-28"
  },
  {
    "id": "1",
    "name": "07 a 50 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.87,
    "availability": 97.0,
    "comfort": 92.5,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "2",
    "name": "R24.05-FLORIPA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.13,
    "availability": 96.3,
    "comfort": 91.3,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "3",
    "name": "R24.09-NOVA IORQUE",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.18,
    "availability": 95.0,
    "comfort": 90.1,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "4",
    "name": "SECRETÁRIA 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 86.1,
    "availability": 86.8,
    "comfort": 78.9,
    "performance": 85.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "5",
    "name": "SECRETÁRIA 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 85.95,
    "availability": 85.5,
    "comfort": 77.7,
    "performance": 88.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "6",
    "name": "R24.04-SÃO PAULO",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.28,
    "availability": 97.3,
    "comfort": 86.5,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "7",
    "name": "ÁREA VIP 04",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 87.8,
    "availability": 88.5,
    "comfort": 82.5,
    "performance": 86.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "8",
    "name": "ÁREA VIP 03",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.38,
    "availability": 95.3,
    "comfort": 91.3,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "9",
    "name": "ÁREA VIP 01",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.22,
    "availability": 94.0,
    "comfort": 90.1,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "10",
    "name": "ÁREA VIP 02",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.48,
    "availability": 93.3,
    "comfort": 88.9,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "11",
    "name": "R24.01-SÃO CARLOS 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.28,
    "availability": 97.0,
    "comfort": 87.7,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "12",
    "name": "R24.01-SÃO CARLOS 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.53,
    "availability": 96.3,
    "comfort": 86.5,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "13",
    "name": "R24.02-COSTA MESA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.17,
    "availability": 95.0,
    "comfort": 92.5,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "14",
    "name": "R24.03-LONDRES 1",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.43,
    "availability": 94.3,
    "comfort": 91.3,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "15",
    "name": "R24.03-LONDRES 2",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.47,
    "availability": 93.0,
    "comfort": 90.1,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "16",
    "name": "COPA EXECUTIVA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 90.93,
    "availability": 94.3,
    "comfort": 84.9,
    "performance": 88.5,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "17",
    "name": "RECEPÇÃO 3",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 87.0,
    "availability": 88.5,
    "comfort": 77.7,
    "performance": 88.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "18",
    "name": "R24.06-RECIFE",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.58,
    "availability": 95.3,
    "comfort": 86.5,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "19",
    "name": "R24.12-AUSTRÁLIA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 90.88,
    "availability": 91.0,
    "comfort": 88.5,
    "performance": 89.5,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "20",
    "name": "R24.10-BLUMENAU",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.68,
    "availability": 93.3,
    "comfort": 91.3,
    "performance": 91.0,
    "status": "Verde",
    "mttr": 2.85,
    "totalOccurrences": 1,
    "criticalOccurrences": 1,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "21",
    "name": "R24.08-NOVA LIMA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 94.27,
    "availability": 97.0,
    "comfort": 90.1,
    "performance": 94.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "22",
    "name": "R24.07-BRASÍLIA",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 93.53,
    "availability": 96.3,
    "comfort": 88.9,
    "performance": 93.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "23",
    "name": "R24.11-DUBLIN",
    "type": "VRV",
    "area": "midea_4",
    "client": "Serasa Experian",
    "health": 92.58,
    "availability": 95.0,
    "comfort": 87.7,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "24",
    "name": "133 a 157 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 93.15,
    "availability": 95.0,
    "comfort": 90.0,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "25",
    "name": "JANELA 01",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 92.21,
    "availability": 94.0,
    "comfort": 88.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "26",
    "name": "125 a 132 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.12,
    "availability": 92.6,
    "comfort": 87.0,
    "performance": 89.8,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "27",
    "name": "109 a 124 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.18,
    "availability": 91.6,
    "comfort": 85.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "28",
    "name": "JANELA 02",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 87.42,
    "availability": 87.2,
    "comfort": 80.0,
    "performance": 89.5,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "29",
    "name": "93 a 108 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.12,
    "availability": 95.2,
    "comfort": 82.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "30",
    "name": "RECEPÇÃO 1",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 85.97,
    "availability": 86.3,
    "comfort": 80.0,
    "performance": 83.8,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "31",
    "name": "RECEPÇÃO 2",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 85.02,
    "availability": 85.3,
    "comfort": 78.5,
    "performance": 82.7,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "32",
    "name": "SALA DE ENTREVISTA",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 84.81,
    "availability": 83.9,
    "comfort": 77.0,
    "performance": 86.0,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "33",
    "name": "R24.13-REUNIÃO 13",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 87.65,
    "availability": 87.4,
    "comfort": 81.5,
    "performance": 88.4,
    "status": "Amarelo",
    "mttr": 7.75,
    "totalOccurrences": 15,
    "criticalOccurrences": 15,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "34",
    "name": "R24.14-REUNIÃO 14",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 86.76,
    "availability": 87.5,
    "comfort": 81.5,
    "performance": 83.8,
    "status": "Amarelo",
    "mttr": 5.3,
    "totalOccurrences": 8,
    "criticalOccurrences": 8,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "35",
    "name": "71 a 86 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.27,
    "availability": 94.0,
    "comfort": 82.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "36",
    "name": "JANELA 03",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 92.31,
    "availability": 92.6,
    "comfort": 90.0,
    "performance": 92.0,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "37",
    "name": "61 a 70 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.37,
    "availability": 91.6,
    "comfort": 88.5,
    "performance": 90.9,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "38",
    "name": "51 a 60 - ESCRITÓRIO",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 90.28,
    "availability": 90.2,
    "comfort": 87.0,
    "performance": 89.8,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "39",
    "name": "CABINES 01 E 02",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 91.44,
    "availability": 95.2,
    "comfort": 85.5,
    "performance": 88.7,
    "status": "Verde",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  },
  {
    "id": "40",
    "name": "JANELA 04",
    "type": "VRV",
    "area": "midea_7",
    "client": "Serasa Experian",
    "health": 88.68,
    "availability": 90.8,
    "comfort": 80.0,
    "performance": 89.5,
    "status": "Amarelo",
    "mttr": 0.0,
    "totalOccurrences": 0,
    "criticalOccurrences": 0,
    "moderateOccurrences": 0,
    "informativeOccurrences": 0,
    "lastUpdated": "2026-06-23",
    "monthKey": "2026-06",
    "month": "Jun/26",
    "startDate": "2026-06-02",
    "endDate": "2026-06-23"
  }
];

export const mockWeeklyUpdates: WeeklyUpdate[] = [
  {
    "id": "1",
    "date": "2026-06-29",
    "title": "Importacao do Log de Alarmes",
    "content": "Foram incorporados 70 registros reais de alarmes disponiveis na base para o cliente Serasa Experian, com destaque para os equipamentos mais reincidentes.",
    "author": "Carlos Santos"
  },
  {
    "id": "2",
    "date": "2026-06-28",
    "title": "Ranking por Equipamento",
    "content": "O dashboard agora prioriza o ranking dos equipamentos com maior recorrencia de alarmes para apoiar o follow-up operacional.",
    "author": "Maria Oliveira"
  },
  {
    "id": "3",
    "date": "2026-06-27",
    "title": "Estrutura Pronta para Novos Dados",
    "content": "A base esta preparada para receber os proximos dados operacionais, alarmes recorrentes e indicadores de desempenho por equipamento.",
    "author": "Joao Silva"
  }
];

export const mockAlarms: Alarm[] = [
  {
    "id": "1",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme 4# registrado com severidade High.",
    "status": "pending_followup",
    "priority": 3,
    "createdAt": "2026-06-23 16:10",
    "updatedAt": "2026-06-23 17:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 30
  },
  {
    "id": "2",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-23 14:35",
    "updatedAt": "2026-06-23 14:45",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "3",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-23 14:05",
    "updatedAt": "2026-06-23 14:20",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "4",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "pending_followup",
    "priority": 1,
    "createdAt": "2026-06-22 20:00",
    "updatedAt": "2026-06-22 20:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 38
  },
  {
    "id": "5",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-17 17:15",
    "updatedAt": "2026-06-17 17:30",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "6",
    "equipmentId": "20",
    "equipmentName": "R24.10-BLUMENAU",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "open",
    "priority": 1,
    "createdAt": "2026-06-15 21:50",
    "updatedAt": "2026-06-15 22:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_4",
    "hasFollowup": false,
    "followupCount": 1
  },
  {
    "id": "7",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-11 12:45",
    "updatedAt": "2026-06-11 13:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "8",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-11 12:05",
    "updatedAt": "2026-06-11 12:20",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "9",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-11 11:30",
    "updatedAt": "2026-06-11 11:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "10",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-11 10:55",
    "updatedAt": "2026-06-11 11:10",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "11",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-10 17:45",
    "updatedAt": "2026-06-10 18:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "12",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-10 17:45",
    "updatedAt": "2026-06-10 18:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "13",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-10 16:40",
    "updatedAt": "2026-06-10 16:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "14",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-10 16:40",
    "updatedAt": "2026-06-10 16:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "15",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-03 16:20",
    "updatedAt": "2026-06-03 16:35",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "16",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-03 15:45",
    "updatedAt": "2026-06-03 16:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "17",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-03 15:20",
    "updatedAt": "2026-06-03 15:30",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "18",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-03 14:45",
    "updatedAt": "2026-06-03 14:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "19",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-03 14:20",
    "updatedAt": "2026-06-03 14:30",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "20",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-02 13:10",
    "updatedAt": "2026-06-02 13:25",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "21",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-02 12:30",
    "updatedAt": "2026-06-02 12:45",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "22",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-02 12:00",
    "updatedAt": "2026-06-02 12:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "23",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-02 11:30",
    "updatedAt": "2026-06-02 11:40",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "24",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-06-02 11:05",
    "updatedAt": "2026-06-02 11:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "25",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 18:55",
    "updatedAt": "2026-05-28 18:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "26",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 18:50",
    "updatedAt": "2026-05-28 18:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "27",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 18:20",
    "updatedAt": "2026-05-28 18:20",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "28",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 17:40",
    "updatedAt": "2026-05-28 17:40",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "29",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 13:55",
    "updatedAt": "2026-05-28 13:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "30",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 13:25",
    "updatedAt": "2026-05-28 13:25",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "31",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-28 12:50",
    "updatedAt": "2026-05-28 12:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "32",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-25 18:25",
    "updatedAt": "2026-05-25 18:25",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "33",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-25 17:50",
    "updatedAt": "2026-05-25 17:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "34",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-25 17:00",
    "updatedAt": "2026-05-25 17:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "35",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-22 09:15",
    "updatedAt": "2026-05-22 09:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "36",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-21 16:15",
    "updatedAt": "2026-05-21 16:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "37",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-21 15:45",
    "updatedAt": "2026-05-21 15:45",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "38",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-21 15:05",
    "updatedAt": "2026-05-21 15:05",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "39",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-21 14:35",
    "updatedAt": "2026-05-21 14:35",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "40",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-20 18:55",
    "updatedAt": "2026-05-20 18:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "41",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-20 18:25",
    "updatedAt": "2026-05-20 18:25",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "42",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-20 10:35",
    "updatedAt": "2026-05-20 10:35",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "43",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 18:55",
    "updatedAt": "2026-05-19 18:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "44",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 18:20",
    "updatedAt": "2026-05-19 18:20",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "45",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 17:50",
    "updatedAt": "2026-05-19 17:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "46",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 17:15",
    "updatedAt": "2026-05-19 17:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "47",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 16:15",
    "updatedAt": "2026-05-19 16:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "48",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 15:20",
    "updatedAt": "2026-05-19 15:20",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "49",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 14:30",
    "updatedAt": "2026-05-19 14:30",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "50",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-19 13:50",
    "updatedAt": "2026-05-19 13:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 29
  },
  {
    "id": "51",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-18 17:50",
    "updatedAt": "2026-05-18 17:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "52",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-18 13:40",
    "updatedAt": "2026-05-18 13:40",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "53",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-18 13:05",
    "updatedAt": "2026-05-18 13:05",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "54",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-18 11:25",
    "updatedAt": "2026-05-18 11:25",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "55",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-18 10:45",
    "updatedAt": "2026-05-18 10:45",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "56",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-14 21:55",
    "updatedAt": "2026-05-14 21:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "57",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-14 21:15",
    "updatedAt": "2026-05-14 21:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "58",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-14 20:45",
    "updatedAt": "2026-05-14 20:45",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "59",
    "equipmentId": "19",
    "equipmentName": "R24.12-AUSTRÁLIA",
    "type": "critical",
    "message": "Alarme 4F registrado com severidade High.",
    "status": "open",
    "priority": 2,
    "createdAt": "2026-05-14 11:30",
    "updatedAt": "2026-05-14 11:30",
    "clientName": "Serasa Experian",
    "areaName": "midea_4",
    "hasFollowup": false,
    "followupCount": 1
  },
  {
    "id": "60",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-14 10:10",
    "updatedAt": "2026-05-14 10:10",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "61",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-13 21:55",
    "updatedAt": "2026-05-13 21:55",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "62",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-13 21:20",
    "updatedAt": "2026-05-13 21:20",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "63",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-13 20:45",
    "updatedAt": "2026-05-13 20:45",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "64",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-13 20:15",
    "updatedAt": "2026-05-13 20:15",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "65",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-12 17:50",
    "updatedAt": "2026-05-12 17:50",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "66",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-12 13:00",
    "updatedAt": "2026-05-12 13:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "67",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-12 12:25",
    "updatedAt": "2026-05-12 12:25",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "68",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-12 12:00",
    "updatedAt": "2026-05-12 12:00",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "69",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-11 18:35",
    "updatedAt": "2026-05-11 18:35",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  },
  {
    "id": "70",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "critical",
    "message": "Alarme P0 registrado com severidade High.",
    "status": "acknowledged",
    "priority": 1,
    "createdAt": "2026-05-11 18:10",
    "updatedAt": "2026-05-11 18:10",
    "clientName": "Serasa Experian",
    "areaName": "midea_7",
    "hasFollowup": true,
    "followupCount": 37
  }
];

export const mockPredictiveTasks: PredictiveTask[] = [
  {
    "id": "1",
    "equipmentId": "34",
    "equipmentName": "R24.14-REUNIÃO 14",
    "type": "inspection",
    "title": "Analise Tecnica - R24.14 Reuniao 14",
    "description": "Analise preditiva concentrada na recorrencia de alarmes P0 e na incapacidade de atingir o setpoint.",
    "technicalAnalysis": "A unidade apresenta forte indicio de anomalia no controle da expansao do refrigerante, com suspeita prioritaria de falha mecanica ou vazamento interno da valvula de expansao eletronica (EEV).",
    "detailedAnalysis": [
      "Durante o periodo analisado a unidade permaneceu em operacao com recorrencia de alarmes de incapacidade de atingir o setpoint.",
      "Os sensores do evaporador apresentaram queda progressiva de temperatura ate aproximadamente -12°C, enquanto a EEV operou frequentemente proxima da abertura maxima, em torno de 304 pls.",
      "Mesmo apos alteracao da velocidade do ventilador para FAN HIGH, os sensores continuaram reduzindo para temperaturas negativas, o que reduz a probabilidade de falha primaria por ventilacao insuficiente.",
      "Os indicios apontam para anomalia no controle da expansao do refrigerante, com forte suspeita de falha mecanica ou vazamento interno da EEV, hipotese que deve ser priorizada na inspecao corretiva.",
      "Como a unidade pertence ao mesmo sistema da Reuniao 13 e apresenta comportamento semelhante, recomenda-se complementar a investigacao com a avaliacao da estrategia de controle da condensadora e do circuito frigorifico."
    ],
    "priority": "high",
    "dueDate": "2026-07-05",
    "status": "in_progress",
    "riskScore": 95,
    "estimatedCost": 4800
  },
  {
    "id": "2",
    "equipmentId": "33",
    "equipmentName": "R24.13-REUNIÃO 13",
    "type": "inspection",
    "title": "Analise Tecnica - R24.13 Reuniao 13",
    "description": "Analise preditiva focada na repetibilidade da anomalia operacional e na abertura elevada da EEV ao longo do ciclo.",
    "technicalAnalysis": "A unidade apresenta comportamento operacional semelhante ao da Reuniao 14, reforcando a suspeita de anomalia no circuito de expansao e a necessidade de validar tambem a influencia sistemica do conjunto condensador.",
    "detailedAnalysis": [
      "Foi identificado comportamento operacional semelhante ao da unidade R24.14, com alerta recorrente de nao atendimento ao setpoint e operacao continua em modo COOL.",
      "Durante a analise, a temperatura ambiente permaneceu proxima de 19°C a 20°C, enquanto os sensores do evaporador reduziram ate aproximadamente -6°C durante a operacao.",
      "A EEV operou entre aproximadamente 200 e 304 pls, mantendo elevada abertura durante boa parte do ciclo, sem variacoes significativas na corrente do compressor que justificassem o comportamento observado.",
      "Em 26/06/2026 foi novamente registrado o mesmo alerta operacional, mantendo-se a EEV em 304 pls e o ambiente sem atingir a condicao de controle esperada.",
      "A repetibilidade da anomalia ao longo dos dias descarta ocorrencia pontual e reforca a recomendacao de inspecao da EEV, dos comandos eletricos associados e da estrategia de controle da unidade condensadora."
    ],
    "priority": "high",
    "dueDate": "2026-07-05",
    "status": "pending",
    "riskScore": 95,
    "estimatedCost": 4800
  }
];

export const mockSystemRankings: SystemRanking[] = [
  {
    "clientName": "Serasa Experian",
    "systemName": "midea_7 • R24.14-REUNIÃO 14",
    "totalAlarms": 38,
    "criticalAlarms": 38,
    "healthScore": 77.91,
    "availability": 77.0,
    "id": "1",
    "rank": 1,
    "trend": "down"
  },
  {
    "clientName": "Serasa Experian",
    "systemName": "midea_7 • R24.13-REUNIÃO 13",
    "totalAlarms": 30,
    "criticalAlarms": 30,
    "healthScore": 83.22,
    "availability": 82.15,
    "id": "2",
    "rank": 2,
    "trend": "stable"
  },
  {
    "clientName": "Serasa Experian",
    "systemName": "midea_4 • R24.12-AUSTRÁLIA",
    "totalAlarms": 1,
    "criticalAlarms": 1,
    "healthScore": 90.58,
    "availability": 90.65,
    "id": "3",
    "rank": 3,
    "trend": "up"
  },
  {
    "clientName": "Serasa Experian",
    "systemName": "midea_4 • R24.10-BLUMENAU",
    "totalAlarms": 1,
    "criticalAlarms": 1,
    "healthScore": 92.68,
    "availability": 93.3,
    "id": "4",
    "rank": 4,
    "trend": "up"
  }
];

export const mockEnergyData: EnergyData[] = [];

export const mockIEERData: IEERData[] = [];

export const mockWaterData: WaterData[] = [];

export const mockHealthTrend: HealthTrendData[] = [
  {
    "month": "Mai/26",
    "health": 86.17,
    "target": 90
  },
  {
    "month": "Jun/26",
    "health": 89.03,
    "target": 90
  }
];

export const mockUptimeData: UptimeData[] = [
  {
    "month": "Mai/26",
    "availability": 85.95
  },
  {
    "month": "Jun/26",
    "availability": 89.4
  }
];
